
import { BibleBook } from './types';

export const BIBLE_BOOKS: BibleBook[] = [
  // Antigo Testamento
  { id: 'genesis', name: 'Gênesis', testament: 'Old', chaptersCount: 50 },
  { id: 'exodo', name: 'Êxodo', testament: 'Old', chaptersCount: 40 },
  { id: 'levitico', name: 'Levítico', testament: 'Old', chaptersCount: 27 },
  { id: 'numeros', name: 'Números', testament: 'Old', chaptersCount: 36 },
  { id: 'deuteronomio', name: 'Deuteronômio', testament: 'Old', chaptersCount: 34 },
  { id: 'josue', name: 'Josué', testament: 'Old', chaptersCount: 24 },
  { id: 'juizes', name: 'Juízes', testament: 'Old', chaptersCount: 21 },
  { id: 'rute', name: 'Rute', testament: 'Old', chaptersCount: 4 },
  { id: '1-samuel', name: '1 Samuel', testament: 'Old', chaptersCount: 31 },
  { id: '2-samuel', name: '2 Samuel', testament: 'Old', chaptersCount: 24 },
  { id: '1-reis', name: '1 Reis', testament: 'Old', chaptersCount: 22 },
  { id: '2-reis', name: '2 Reis', testament: 'Old', chaptersCount: 25 },
  { id: '1-cronicas', name: '1 Crônicas', testament: 'Old', chaptersCount: 29 },
  { id: '2-cronicas', name: '2 Crônicas', testament: 'Old', chaptersCount: 36 },
  { id: 'esdras', name: 'Esdras', testament: 'Old', chaptersCount: 10 },
  { id: 'neemias', name: 'Neemias', testament: 'Old', chaptersCount: 13 },
  { id: 'ester', name: 'Ester', testament: 'Old', chaptersCount: 10 },
  { id: 'jo', name: 'Jó', testament: 'Old', chaptersCount: 42 },
  { id: 'salmos', name: 'Salmos', testament: 'Old', chaptersCount: 150 },
  { id: 'proverbios', name: 'Provérbios', testament: 'Old', chaptersCount: 31 },
  { id: 'eclesiastes', name: 'Eclesiastes', testament: 'Old', chaptersCount: 12 },
  { id: 'canticos', name: 'Cânticos', testament: 'Old', chaptersCount: 8 },
  { id: 'isaias', name: 'Isaías', testament: 'Old', chaptersCount: 66 },
  { id: 'jeremias', name: 'Jeremias', testament: 'Old', chaptersCount: 52 },
  { id: 'lamentacoes', name: 'Lamentações', testament: 'Old', chaptersCount: 5 },
  { id: 'ezequiel', name: 'Ezequiel', testament: 'Old', chaptersCount: 48 },
  { id: 'daniel', name: 'Daniel', testament: 'Old', chaptersCount: 12 },
  { id: 'oseias', name: 'Oseias', testament: 'Old', chaptersCount: 14 },
  { id: 'joel', name: 'Joel', testament: 'Old', chaptersCount: 3 },
  { id: 'amos', name: 'Amós', testament: 'Old', chaptersCount: 9 },
  { id: 'obadias', name: 'Obadias', testament: 'Old', chaptersCount: 1 },
  { id: 'jonas', name: 'Jonas', testament: 'Old', chaptersCount: 4 },
  { id: 'miqueias', name: 'Miqueias', testament: 'Old', chaptersCount: 7 },
  { id: 'naum', name: 'Naum', testament: 'Old', chaptersCount: 3 },
  { id: 'habacuque', name: 'Habacuque', testament: 'Old', chaptersCount: 3 },
  { id: 'sofonias', name: 'Sofonias', testament: 'Old', chaptersCount: 3 },
  { id: 'ageu', name: 'Ageu', testament: 'Old', chaptersCount: 2 },
  { id: 'zacarias', name: 'Zacarias', testament: 'Old', chaptersCount: 14 },
  { id: 'malaquias', name: 'Malaquias', testament: 'Old', chaptersCount: 4 },
  
  // Novo Testamento
  { id: 'mateus', name: 'Mateus', testament: 'New', chaptersCount: 28 },
  { id: 'marcos', name: 'Marcos', testament: 'New', chaptersCount: 16 },
  { id: 'lucas', name: 'Lucas', testament: 'New', chaptersCount: 24 },
  { id: 'joao', name: 'João', testament: 'New', chaptersCount: 21 },
  { id: 'atos', name: 'Atos', testament: 'New', chaptersCount: 28 },
  { id: 'romanos', name: 'Romanos', testament: 'New', chaptersCount: 16 },
  { id: '1-corintios', name: '1 Coríntios', testament: 'New', chaptersCount: 16 },
  { id: '2-corintios', name: '2 Coríntios', testament: 'New', chaptersCount: 13 },
  { id: 'galatas', name: 'Gálatas', testament: 'New', chaptersCount: 6 },
  { id: 'efesios', name: 'Efésios', testament: 'New', chaptersCount: 6 },
  { id: 'filipenses', name: 'Filipenses', testament: 'New', chaptersCount: 4 },
  { id: 'colossenses', name: 'Colossenses', testament: 'New', chaptersCount: 4 },
  { id: '1-tessalonicenses', name: '1 Tessalonicenses', testament: 'New', chaptersCount: 5 },
  { id: '2-tessalonicenses', name: '2 Tessalonicenses', testament: 'New', chaptersCount: 3 },
  { id: '1-timoteo', name: '1 Timóteo', testament: 'New', chaptersCount: 6 },
  { id: '2-timoteo', name: '2 Timóteo', testament: 'New', chaptersCount: 4 },
  { id: 'tito', name: 'Tito', testament: 'New', chaptersCount: 3 },
  { id: 'filemon', name: 'Filemon', testament: 'New', chaptersCount: 1 },
  { id: 'hebreus', name: 'Hebreus', testament: 'New', chaptersCount: 13 },
  { id: 'tiago', name: 'Tiago', testament: 'New', chaptersCount: 5 },
  { id: '1-pedro', name: '1 Pedro', testament: 'New', chaptersCount: 5 },
  { id: '2-pedro', name: '2 Pedro', testament: 'New', chaptersCount: 3 },
  { id: '1-joao', name: '1 João', testament: 'New', chaptersCount: 5 },
  { id: '2-joao', name: '2 João', testament: 'New', chaptersCount: 1 },
  { id: '3-joao', name: '3 João', testament: 'New', chaptersCount: 1 },
  { id: 'judas', name: 'Judas', testament: 'New', chaptersCount: 1 },
  { id: 'apocalipse', name: 'Apocalipse', testament: 'New', chaptersCount: 22 },
];
